### ISSUE TITLE
npm start报错，roadhog server也报错

### ISSUE THREAD

**Issue by ciuji** [Yidadaa/UESTC_Helper#14]
运行npm start报错如下
> HOST=127.0.0.1 roadhog server

'HOST' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `HOST=127.0.0.1 roadhog server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

运行roadhog server会报缩进语法错误。

**Comment by Yidadaa** [comment]
Windows下面会出现这种问题，把`Host=127.0.0.1`删掉就行了，明天我更新一下脚本。
