### ISSUE TITLE
一点小的建议

### ISSUE THREAD

**Issue by Frederick-Zhu** [Yidadaa/UESTC_Helper#2]
被基友安利来的 顺手留个issue

第一是门户有一个隐藏的一周内免登陆的checkbox 被注释掉了但是亲测可用 不知道作者有没有考虑加入一下(⊙v⊙)

在一个是 我看到了重修推荐 想起了以前做的一个半死不活的重修推荐的小脚本_(:зゝ∠)_ 是用py交易（划去）写出来的 不太懂chrome系插件的玩法 要是作者感兴趣可以看一下_(:зゝ∠)_ 

传送：https://github.com/Frederick-Zhu/uestc-portal-util/blob/dev/portal_tool/restudy_suggest.py

因为是从以前的烂代码里摘出来的所以还没来得及整理好_(:зゝ∠)_ 凑活看吧_(:зゝ∠)_

以上

**Comment by Frederick-Zhu** [comment]
唔 找补一下 我想的是能不能把重修的性价比也算在内 这样对于我这种穷孩子来说会贴心一点

再一个就是能不能按照学期再次排序 规避一下正在上正课的重修 毕竟没有正课的内个学期重修要简单不少

唔再有就是成绩柱状图那里 在最上层能不能把60和85两个分数线画个横线压在柱状图上 我觉得一般大家都会更关心这两个成绩 甚至我觉得可以把成绩柱弄成红黄绿（随便想的_(:зゝ∠)_） 60以下红色 85以上绿色之类的 0.0

以上

**Comment by Yidadaa** [comment]
蛤，居然真的有人来看啊……激动……

其实我坠早也是搞的py交易……只是后来要可视化的时候发现又要学一堆gui库，于是弃之……

我也在看你的代码，看到好的功能，会考虑加进去的蛤～

**Comment by Frederick-Zhu** [comment]
Σ( ° △ °|||)︴感觉被钦点了 好激动 怎么能表现的像经常被钦点一样

先给作者+1s（划去）+1 star

**Comment by Yidadaa** [comment]
@Frederick-Zhu Excited! 不过那个重修的规则我还是很晕……是不是如果要重修大一上学期的课程A，上学期重修和下学期重修的价格是不一样的？没有正课那个我也没弄懂（笑哭.jpg）

还有我觉得柱状图这个建议很棒！而且可行性很高，我准备下个版本就加进去！

**Comment by Frederick-Zhu** [comment]
唔 我想的是 比如大一上学的危机坟1 那么重修的时候最好就避开在大二 三 四的上学期重修危机坟1 我觉得要是脸黑容易赶上跟大一一块考 这个难度就比下学期重修要大一些了

ps 宿舍电信网开github简直爆炸 我换了手机流量顿时就好起来了

**Comment by Frederick-Zhu** [comment]
[一个小的demo](http://123.206.51.144:1207/getrestudysuggest)

我还没有做好在对总GPA的提升空间和性价比这两项谁排序优先级更高一点 或者有没有一个算法或者系数把他们俩统一起来_(:зゝ∠)_

**Comment by Frederick-Zhu** [comment]
还有把私钥放到公仓真的没问题么Σ( ° △ °|||)︴

我觉得可以考虑travis ci之类的来负责自动的编译测试

并且可以很好的把私钥藏起来 可以考虑看一下

**Comment by Yidadaa** [comment]
@Frederick-Zhu 这样啊……讲道理我也是新司机……感谢老司机指路！我会改进的！

**Comment by Yidadaa** [comment]
刚才 github 网一直爆炸……现在感觉好多了，重修学期的建议那个我觉着可以改进，还有，你的网站我登录之后显示 unkown error 不知道为什么……

**Comment by Frederick-Zhu** [comment]
我的内个demo我又试了一下 我这边能登上去呀 

可能是在半路被-1s了吧_(:зゝ∠)_
