### ISSUE TITLE
我是来膜拜的

### ISSUE THREAD

**Issue by nilaoda** [Yidadaa/UESTC_Helper#4]
其他学校大一新生……前来膜拜。。请问做一个这样的插件容易吗

**Comment by nilaoda** [comment]
我们学校是URP综合教务系统

**Comment by Yidadaa** [comment]
做这样一个插件只需要有html+css+js的基础就可以了，然后根据[这个文档](https://chajian.baidu.com/developer/extensions/getstarted.html)就可以上手开发了！
而且跟教务系统的类型无关，大致流程就是 抓包->解包->模拟请求->解析数据->展示 。

有问题可以直接问我！看来你们学校也要有插件可以用了！

**Comment by nilaoda** [comment]
谢谢！
