### ISSUE TITLE
同学求认识～

### ISSUE THREAD

**Issue by wangning0** [Yidadaa/UESTC_Helper#6]
对你这个的很感兴趣，想认识下，交个朋友可以吗？我也是uestc的

**Comment by Yidadaa** [comment]
如果你对本插件感兴趣，可以fork我的项目并提交代码哈！

想认识我的话，我的QQ是1143922395，直接添加我为好友就可以了，欢迎一起来交流技术！

**Comment by wangning0** [comment]
阿里嘎多！

**Comment by wangning0** [comment]
其实我觉得如果你能加上一个期末考试结束后，可以做一个成绩出来后的消息提醒，说不定会更好～
