### ISSUE TITLE
如果我想看原教务系统的东西怎么办呢

### ISSUE THREAD

**Issue by vimt** [Yidadaa/UESTC_Helper#7]
首先  先献上我的膝盖  确实做了众多基大人想做而没有做的事情
然后说个小问题
比如说我想看我的计划  我要评教什么的  或者原信息门户的信息公告
个人建议  最简单的。。加一个切换到原版的功能
或者做一个弹框把原来的页面显示出来，
或者。。复杂一点。。把信息门户有的功能都优化一遍 _(:з」∠)_ 
或者还有更好的解决方案
最后  加油！

**Comment by Yidadaa** [comment]
目前有切换按钮的，点击浏览器扩展栏的图标就能看到了！
下一步准备加入评教和选课功能，公告功能可能要放到以后来实现了，希望谅解，毕竟我这拖延症晚期……

**Comment by Yidadaa** [comment]
![测试图片](http://img.blog.csdn.net/20140205132207421)

**Comment by vimt** [comment]
哦哦 没看到x.x  多年眼瞎依然没有好
close吧。。
